//
//  EntypoLabel.h
//  Engager
//
//  Created by Lee Probert on 31/05/2013.
//  Copyright (c) 2013 Agnitio. All rights reserved.
//

/*
    This label is designed to be used with the Entypo.ttf font.
    It has a bunch of icon glyphs. There is a guide in the resources folder of this project (not bundled).
 
 http://www.entypo.com/
 
 248 - icons
 46 - social icons
 
 */

typedef enum entypoIconType {
    
    EntypoIconTypePhone,
    EntypoIconTypeMobile,
    EntypoIconTypeMouse,
    EntypoIconTypeAddress,
    EntypoIconTypeMail,
    EntypoIconTypePaperPlane,
    EntypoIconTypePencil,
    EntypoIconTypeFeather,
    EntypoIconTypeAttach,
    EntypoIconTypeInbox,
    EntypoIconTypeReply,
    EntypoIconTypereplyAll,
    EntypoIconTypeForward,
    EntypoIconTypeUser,
    EntypoIconTypeUsers,
    EntypoIconTypeAddUser,
    EntypoIconTypeVCard,
    EntypoIconTypeExport,
    EntypoIconTypeLocation,
    EntypoIconTypeMap,
    EntypoIconTypeCompass,
    EntypoIconTypeDirection,
    EntypoIconTypeHaircross,
    EntypoIconTypeShare,
    EntypoIconTypeShareable,
    EntypoIconTypeHeart,
    EntypoIconTypeHeartEmpty,
    EntypoIconTypeStar,
    EntypoIconTypeStarEmpty,
    EntypoIconTypeThumbsUp,
    EntypoIconTypeThumbsDown,
    EntypoIconTypeChat,
    EntypoIconTypeComment,
    EntypoIconTypeQuote,
    EntypoIconTypeHome,
    EntypoIconTypePopup,
    EntypoIconTypeSearch,
    EntypoIconTypeFlashlight,
    EntypoIconTypePrint,
    EntypoIconTypeBell,
    EntypoIconTypeLink,
    EntypoIconTypeFlag,
    EntypoIconTypeCog,
    EntypoIconTypeTools,
    EntypoIconTypeTrophy,
    EntypoIconTypeTag,
    EntypoIconTypeCamera,
    EntypoIconTypeMegaphone,
    EntypoIconTypeMoon,
    EntypoIconTypePalette,
    EntypoIconTypeLeaf,
    EntypoIconTypeNote,
    EntypoIconTypeBeamedNote,
    EntypoIconTypeNew,
    EntypoIconTypeGraduationCap,
    EntypoIconTypeBook,
    EntypoIconTypeNewspaper,
    EntypoIconTypeBag,
    EntypoIconTypeAirplane,
    EntypoIconTypeLifebuoy,
    EntypoIconTypeEye,
    EntypoIconTypeClock,
    EntypoIconTypeMic,
    EntypoIconTypeCalendar,
    EntypoIconTypeFlash,
    EntypoIconTypeThunderCloud,
    EntypoIconTypeDroplet,
    EntypoIconTypeCD,
    EntypoIconTypeBriefcase,
    EntypoIconTypeAir,
    EntypoIconTypeHourglass,
    EntypoIconTypeGauge,
    EntypoIconTypeLanguage,
    EntypoIconTypeNetwork,
    EntypoIconTypeKey,
    EntypoIconTypeBattery,
    EntypoIconTypeBucket,
    EntypoIconTypeMagnet,
    EntypoIconTypeDrive,
    EntypoIconTypeCup,
    EntypoIconTypeRocket,
    EntypoIconTypeBrush,
    EntypoIconTypeSuitcase,
    EntypoIconTypeTrafficCone,
    EntypoIconTypeGlobe,
    EntypoIconTypeKeyboard,
    EntypoIconTypeBrowser,
    EntypoIconTypePublish,
    EntypoIconTypeProgress3,
    EntypoIconTypeProgress2,
    EntypoIconTypeProgress1,
    EntypoIconTypeProgress0,
    EntypoIconTypeLightDown,
    EntypoIconTypeLightUp,
    EntypoIconTypeAdjust,
    EntypoIconTypeCode,
    EntypoIconTypeMonitor,
    EntypoIconTypeInfinity,
    EntypoIconTypeLightBulb,
    EntypoIconTypeCreditCard,
    EntypoIconTypeDatabase,
    EntypoIconTypeVoicemail,
    EntypoIconTypeClipboard,
    EntypoIconTypeCart,
    EntypoIconTypeBox,
    EntypoIconTypeTicket,
    EntypoIconTypeRSS,
    EntypoIconTypeSignal,
    EntypoIconTypeThermometer,
    EntypoIconTypeWater,
    EntypoIconTypeSweden,
    EntypoIconTypeLineGraph,
    EntypoIconTypePieChart,
    EntypoIconTypeBarGraph,
    EntypoIconTypeAreaGraph,
    EntypoIconTypeLock,
    EntypoIconTypeLockOpen,
    EntypoIconTypeLogout,
    EntypoIconTypeLogin,
    EntypoIconTypeCheck,
    EntypoIconTypeCross,
    EntypoIconTypeSquaredMinus,
    EntypoIconTypeSquaredPlus,
    EntypoIconTypeSquaredCross,
    EntypoIconTypeCircledMinus,
    EntypoIconTypeCircledPlus,
    EntypoIconTypeCircledCross,
    EntypoIconTypeMinus,
    EntypoIconTypePlus,
    EntypoIconTypeErase,
    EntypoIconTypeBlock,
    EntypoIconTypeInfo,
    EntypoIconTypeCircledInfo,
    EntypoIconTypeHelp,
    EntypoIconTypeCircledHelp,
    EntypoIconTypeWarning,
    EntypoIconTypeCycle,
    EntypoIconTypeCW,
    EntypoIconTypeCCW,
    EntypoIconTypeShuffle,
    EntypoIconTypeBack,
    EntypoIconTypeLevelDown,
    EntypoIconTypeRetweet,
    EntypoIconTypeLoop,
    EntypoIconTypeBackInTime,
    EntypoIconTypeLevelUp,
    EntypoIconTypeSwitch,
    EntypoIconTypeNumberedList,
    EntypoIconTypeAddtoList,
    EntypoIconTypeLayout,
    EntypoIconTypeList,
    EntypoIconTypeTextDoc,
    EntypoIconTypeTextDocInverted,
    EntypoIconTypeDoc,
    EntypoIconTypeDocs,
    EntypoIconTypeLandscapeDoc,
    EntypoIconTypePicture,
    EntypoIconTypeVideo,
    EntypoIconTypeMusic,
    EntypoIconTypeFolder,
    EntypoIconTypeArchive,
    EntypoIconTypeTrash,
    EntypoIconTypeUpload,
    EntypoIconTypeDownload,
    EntypoIconTypeSave,
    EntypoIconTypeInstall,
    EntypoIconTypeCloud,
    EntypoIconTypeUploadCloud,
    EntypoIconTypeBookmark,
    EntypoIconTypeBookmarks,
    EntypoIconTypeOpenBook,
    EntypoIconTypePlay,
    EntypoIconTypePause,
    EntypoIconTypeRecord,
    EntypoIconTypeStop,
    EntypoIconTypeFF,
    EntypoIconTypeFB,
    EntypoIconTypeToStart,
    EntypoIconTypeToEnd,
    EntypoIconTypeResizeFull,
    EntypoIconTypeResizeSmall,
    EntypoIconTypeVolume,
    EntypoIconTypeSound,
    EntypoIconTypeMute,
    EntypoIconTypeFlowCascade,
    EntypoIconTypeFlowBranch,
    EntypoIconTypeFlowTree,
    EntypoIconTypeFlowLine,
    EntypoIconTypeFlowParallel,
    EntypoIconTypeLeftBold,
    EntypoIconTypeDownBold,
    EntypoIconTypeUpBold,
    EntypoIconTypeRightBold,
    EntypoIconTypeLeft,
    EntypoIconTypeDown,
    EntypoIconTypeUp,
    EntypoIconTypeRight,
    EntypoIconTypeCircledLeft,
    EntypoIconTypeCircledDown,
    EntypoIconTypeCircledUp,
    EntypoIconTypeCircledRight,
    EntypoIconTypeTriangleLeft,
    EntypoIconTypeTriangleDown,
    EntypoIconTypeTriangleUp,
    EntypoIconTypeTriangleRight,
    EntypoIconTypeChevronLeft,
    EntypoIconTypeChevronDown,
    EntypoIconTypeChevronUp,
    EntypoIconTypeChevronRight,
    EntypoIconTypeChevronSmallLeft,
    EntypoIconTypeChevronSmallDown,
    EntypoIconTypeChevronSmallUp,
    EntypoIconTypeChevronSmallRight,
    EntypoIconTypeChevronThinLeft,
    EntypoIconTypeChevronThinDown,
    EntypoIconTypeChevronThinUp,
    EntypoIconTypeChevronThinRight,
    EntypoIconTypeLeftThin,
    EntypoIconTypeDownThin,
    EntypoIconTypeUpThin,
    EntypoIconTypeRightThin,
    EntypoIconTypeArrowCombo,
    EntypoIconTypeThreeDots,
    EntypoIconTypeTwoDots,
    EntypoIconTypeDot,
    EntypoIconTypeCC,
    EntypoIconTypeCCBY,
    EntypoIconTypeCCNC,
    EntypoIconTypeCCNCEU,
    EntypoIconTypeCCNCJP,
    EntypoIconTypeCCSA,
    EntypoIconTypeCCND,
    EntypoIconTypeCCPD,
    EntypoIconTypeCCZero,
    EntypoIconTypeCCShare,
    EntypoIconTypeCCremix,
    EntypoIconTypeDBLogo,
    EntypoIconTypeDBShape,
    
    EntypoIconSocialTypeGithub,
    EntypoIconSocialTypeCGithub,
    EntypoIconSocialTypeFlickr,
    EntypoIconSocialTypeCFlickr,
    EntypoIconSocialTypeVimeo,
    EntypoIconSocialTypeCVimeo,
    EntypoIconSocialTypeTwitter,
    EntypoIconSocialTypeCTwitter,
    EntypoIconSocialTypeFacebook,
    EntypoIconSocialTypeCFacebook,
    EntypoIconSocialTypeSFacebook,
    EntypoIconSocialTypeGooglePlus,
    EntypoIconSocialTypeCGooglePlus,
    EntypoIconSocialTypePinterest,
    EntypoIconSocialTypeCPinterest,
    EntypoIconSocialTypeTumblr,
    EntypoIconSocialTypeCtumblr,
    EntypoIconSocialTypeLinkedIn,
    EntypoIconSocialTypeClinkedIn,
    EntypoIconSocialTypeDribbble,
    EntypoIconSocialTypeCDribbble,
    EntypoIconSocialTypeStumbleupon,
    EntypoIconSocialTypeCStumbleupon,
    EntypoIconSocialTypeLastFM,
    EntypoIconSocialTypeCLastFM,
    EntypoIconSocialTypeRdio,
    EntypoIconSocialTypeCRdio,
    EntypoIconSocialTypeSpotify,
    EntypoIconSocialTypeCSpotify,
    EntypoIconSocialTypeQQ,
    EntypoIconSocialTypeInstagram,
    EntypoIconSocialTypeDropBox,
    EntypoIconSocialTypeEvernote,
    EntypoIconSocialTypeFlattr,
    EntypoIconSocialTypeSkype,
    EntypoIconSocialTypeCSkype,
    EntypoIconSocialTypeRenren,
    EntypoIconSocialTypeSinaWeibo,
    EntypoIconSocialTypePayPal,
    EntypoIconSocialTypePicasa,
    EntypoIconSocialTypeSoundcloud,
    EntypoIconSocialTypeMixi,
    EntypoIconSocialTypeBehance,
    EntypoIconSocialTypeGoogleCircles,
    EntypoIconSocialTypeVK,
    EntypoIconSocialTypeSmashing
    
} EntypoIconType;

#import <UIKit/UIKit.h>

@interface EntypoLabel : UILabel

@property (nonatomic, assign, getter = isSocial) BOOL social;
@property (nonatomic, strong) NSNumber *numberIconType;

- (void) setIconFromType:(EntypoIconType)type;
- (void) setPointSize:(CGFloat)pointSize;
- (id) initWithFrame:(CGRect)frame iconType:(EntypoIconType)type;

+ (EntypoLabel*) newLabelWithIcon:(EntypoIconType)type;
+ (UIImage*) imageOfIcon:(EntypoIconType)type;
+ (NSString*) stringFromFontSocialType:(BOOL)isSocial iconType:(EntypoIconType)type;

+ (NSInteger) totalIcons;
+ (NSInteger) totalSocialIcons;

@end
